# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
email: me@woutschoovaets.be
description: >- # this means to ignore newlines until "baseurl:"
  Hi, I'm Wout a passionate developer with love for both front-end and back-end. Why am I saying that i'm a passionated developer? Well The answer is rather simple and lies in what I do in my free time. I love to develop in my free time, I often stream on Twitch while developing one of my applications. I watch a lot of tech talks on youtube. (Google IO, Devoxx, NG-Conf, ...). So i'm dedicating a lot of time to programming. Of course most of us needs some sport as well so I play volleyball to let of some steam.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "woutschoovaerts.be" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-minifier
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

jekyll-minifier:
  uglifier_args:
    harmony: true
